language: node_js
node_js:
    - "8"
    - "9"
    - "10"
    - "11"
install:
    - npm install
    - npm install -g jest
    - npm install -g codecov
script:
  - jest --config jest.config.js
  - codecov --token="67668c40-5b24-4f3e-8fe6-319be2c75eab"